CREATE TABLE IF NOT EXISTS goods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(255) NOT NULL,
  description varchar(4096),
  cost double DEFAULT 0.0 CHECK (cost > -1),
  in_stock int DEFAULT 0,
  CONSTRAINT goods_id PRIMARY KEY (id)
);

CREATE TABLE goods_delivery (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title varchar(255),
  product_id bigint,
  amount int,
  CONSTRAINT goods_delivery_id PRIMARY KEY (id)
);

CREATE TABLE goods_sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title varchar(255),
  product_id bigint,
  amount int,
  total_cost double,
  CONSTRAINT goods_sales_id PRIMARY KEY (id)
);

ALTER TABLE goods_delivery ADD FOREIGN KEY (product_id) REFERENCES goods (id);

ALTER TABLE goods_sales ADD FOREIGN KEY (product_id) REFERENCES goods (id);