CREATE TABLE IF NOT EXISTS goods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(255) NOT NULL,
  description varchar(4096),
  cost double DEFAULT 0.0 CHECK (cost > -1),
  in_stock bool DEFAULT FALSE
);